const clubsData = [
    // --- ԱՆԳԼԻԱ (Premier League - Top 7) ---
    { name: "Manchester United", logo: "https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg" },
    { name: "Manchester City", logo: "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg" },
    { name: "Liverpool", logo: "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg" },
    { name: "Arsenal", logo: "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg" },
    { name: "Chelsea", logo: "https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg" },
    { name: "Tottenham", logo: "https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg" },
    { name: "Leicester City", logo: "https://upload.wikimedia.org/wikipedia/en/2/2d/Leicester_City_crest.svg" },
    { name: "Newcastle", logo: "https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg" },
    { name: "Aston Villa", logo: "https://upload.wikimedia.org/wikipedia/en/f/f9/Aston_Villa_FC_crest_%282016%29.svg" },
    { name: "Everton", logo: "https://upload.wikimedia.org/wikipedia/en/7/7c/Everton_FC_logo.svg" },
    { name: "West Ham", logo: "https://upload.wikimedia.org/wikipedia/en/c/c2/West_Ham_United_FC_logo.svg" },
    { name: "Brighton", logo: "https://upload.wikimedia.org/wikipedia/en/f/fd/Brighton_%26_Hove_Albion_logo.svg" },
    { name: "Wolves", logo: "https://upload.wikimedia.org/wikipedia/en/f/fc/Wolverhampton_Wanderers.svg" },
    { name: "Southampton", logo: "https://upload.wikimedia.org/wikipedia/en/c/c9/FC_Southampton.svg" },
    { name: "Blackburn Rovers", logo: "https://upload.wikimedia.org/wikipedia/en/0/0f/Blackburn_Rovers.svg" },
    { name: "Bolton Wanderers", logo: "https://upload.wikimedia.org/wikipedia/en/8/82/Bolton_Wanderers_FC_logo.svg" },

    // --- ԻՍՊԱՆԻԱ (La Liga - Top 7) ---
    { name: "Real Madrid", logo: "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg" },
    { name: "Barcelona", logo: "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_logo.svg" },
    { name: "Atletico Madrid", logo: "https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_madrid_2017_logo.svg" },
    { name: "Sevilla", logo: "https://upload.wikimedia.org/wikipedia/en/3/3b/Sevilla_FC_logo.svg" },
    { name: "Valencia", logo: "https://upload.wikimedia.org/wikipedia/en/c/ce/Valenciacf.svg" },
    { name: "Villarreal", logo: "https://upload.wikimedia.org/wikipedia/en/7/70/Villarreal_CF_logo.svg" },
    { name: "Real Sociedad", logo: "https://upload.wikimedia.org/wikipedia/en/f/f1/Real_Sociedad_logo.svg" },
    { name: "Athletic Bilbao", logo: "https://upload.wikimedia.org/wikipedia/en/9/98/Club_Athletic_Bilbao_logo.svg" },
    { name: "Real Betis", logo: "https://upload.wikimedia.org/wikipedia/en/1/13/Real_betis_logo.svg" },
    { name: "Girona", logo: "https://upload.wikimedia.org/wikipedia/en/9/90/Forca_Girona.svg" },
    { name: "Getafe", logo: "https://upload.wikimedia.org/wikipedia/en/7/7f/Getafe_CF_logo.svg" },
    { name: "Espanyol", logo: "https://upload.wikimedia.org/wikipedia/en/d/d6/RCD_Espanyol_logo.svg" },
    { name: "Malaga", logo: "https://upload.wikimedia.org/wikipedia/en/e/e0/M%C3%A1laga_CF.svg" },
    { name: "Celta Vigo", logo: "https://upload.wikimedia.org/wikipedia/en/1/1b/RC_Celta_de_Vigo_logo.svg" },
    { name: "Osasuna", logo: "https://upload.wikimedia.org/wikipedia/en/d/db/CA_Osasuna_logo.svg" },

    // --- ԻՏԱԼԻԱ (Serie A - Top 7) ---
    { name: "Juventus", logo: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Juventus_FC_2017_icon_%28black%29.svg" },
    { name: "AC Milan", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg" },
    { name: "Inter Milan", logo: "https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021_logo.svg" },
    { name: "Napoli", logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/SSC_Napoli_2021.svg" },
    { name: "Roma", logo: "https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo_%282017%29.svg" },
    { name: "Lazio", logo: "https://upload.wikimedia.org/wikipedia/en/c/ce/S.S._Lazio_badge.svg" },
    { name: "Atalanta", logo: "https://upload.wikimedia.org/wikipedia/en/6/66/Atalanta_BC.svg" },
    { name: "Fiorentina", logo: "https://upload.wikimedia.org/wikipedia/commons/7/79/ACF_Fiorentina_2022_logo.svg" },
    { name: "Udinese", logo: "https://upload.wikimedia.org/wikipedia/en/c/ce/Udinese_Calcio_logo.svg" },
    { name: "Bologna", logo: "https://upload.wikimedia.org/wikipedia/en/5/5b/Bologna_F.C._1909_logo.svg" },
    { name: "Torino", logo: "https://upload.wikimedia.org/wikipedia/en/2/2e/Torino_FC_Logo.svg" },
    { name: "Sampdoria", logo: "https://upload.wikimedia.org/wikipedia/en/d/d2/U.C._Sampdoria_logo.svg" },
    { name: "Palermo", logo: "https://upload.wikimedia.org/wikipedia/en/9/9b/Palermo_F.C._logo.svg" },
    { name: "Parma", logo: "https://upload.wikimedia.org/wikipedia/en/d/d2/Parma_Calcio_1913_logo.svg" },

    // --- ԳԵՐՄԱՆԻԱ (Bundesliga - Top 7) ---
    { name: "Bayern Munich", logo: "https://upload.wikimedia.org/wikipedia/commons/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg" },
    { name: "Dortmund", logo: "https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg" },
    { name: "Bayer Leverkusen", logo: "https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg" },
    { name: "RB Leipzig", logo: "https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg" },
    { name: "Frankfurt", logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/Eintracht_Frankfurt_Logo.svg" },
    { name: "Wolfsburg", logo: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Logo_VfL_Wolfsburg.svg" },
    { name: "Schalke 04", logo: "https://upload.wikimedia.org/wikipedia/commons/6/6d/FC_Schalke_04_Logo.svg" },
    { name: "Monchengladbach", logo: "https://upload.wikimedia.org/wikipedia/commons/8/81/Borussia_M%C3%B6nchengladbach_logo.svg" },
    { name: "Stuttgart", logo: "https://upload.wikimedia.org/wikipedia/commons/e/eb/VfB_Stuttgart_1893_Logo.svg" },
    { name: "Werder Bremen", logo: "https://upload.wikimedia.org/wikipedia/commons/b/be/SV-Werder-Bremen-Logo.svg" },
    { name: "Hoffenheim", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Logo_TSG_Hoffenheim.svg" },
    { name: "Freiburg", logo: "https://upload.wikimedia.org/wikipedia/en/6/6d/SC_Freiburg_logo.svg" },
    { name: "Hertha Berlin", logo: "https://upload.wikimedia.org/wikipedia/en/8/81/Hertha_BSC_Logo_2012.svg" },

    // --- ՖՐԱՆՍԻԱ (Ligue 1 - Top 7) ---
    { name: "PSG", logo: "https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg" },
    { name: "Lyon", logo: "https://upload.wikimedia.org/wikipedia/en/1/1c/Olympique_Lyonnais_logo.svg" },
    { name: "Marseille", logo: "https://upload.wikimedia.org/wikipedia/en/d/d1/Olympique_de_Marseille_logo.svg" },
    { name: "Monaco", logo: "https://upload.wikimedia.org/wikipedia/en/b/ba/AS_Monaco_FC.svg" },
    { name: "Lille", logo: "https://upload.wikimedia.org/wikipedia/en/3/3f/Lille_OSC_2018_logo.svg" },
    { name: "Rennes", logo: "https://upload.wikimedia.org/wikipedia/en/9/9e/Stade_Rennais_FC.svg" },
    { name: "Nice", logo: "https://upload.wikimedia.org/wikipedia/en/2/2e/OGC_Nice_logo.svg" },
    { name: "Lens", logo: "https://upload.wikimedia.org/wikipedia/en/c/cc/RC_Lens_logo.svg" },
    { name: "Saint-Etienne", logo: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Logo_AS_Saint-%C3%89tienne.svg" },
    { name: "Bordeaux", logo: "https://upload.wikimedia.org/wikipedia/en/a/ab/FC_Girondins_de_Bordeaux_logo.svg" },
    { name: "Montpellier", logo: "https://upload.wikimedia.org/wikipedia/en/a/a8/Montpellier_HSC_logo.svg" },
    { name: "Nantes", logo: "https://upload.wikimedia.org/wikipedia/en/1/1b/FC_Nantes_2019_logo.svg" }
];
