const playersData = [
    { name: "Cristiano Ronaldo", clubs: ["Manchester United", "Real Madrid", "Juventus"] },
    { name: "Lionel Messi", clubs: ["Barcelona", "PSG"] },
    { name: "Zlatan Ibrahimovic", clubs: ["Juventus", "Inter Milan", "Barcelona", "AC Milan", "PSG", "Manchester United"] },
    { name: "Ronaldo Nazario", clubs: ["Barcelona", "Inter Milan", "Real Madrid", "AC Milan"] },
    { name: "Ronaldinho", clubs: ["PSG", "Barcelona", "AC Milan"] },
    { name: "Zinedine Zidane", clubs: ["Juventus", "Real Madrid"] },
    { name: "Thierry Henry", clubs: ["Juventus", "Arsenal", "Barcelona"] },
    { name: "Luis Suarez", clubs: ["Liverpool", "Barcelona", "Atletico Madrid"] },
    { name: "Neymar Jr", clubs: ["Barcelona", "PSG"] },
    { name: "Karim Benzema", clubs: ["Lyon", "Real Madrid"] },
    { name: "Gareth Bale", clubs: ["Tottenham", "Real Madrid"] },
    { name: "Luka Modric", clubs: ["Tottenham", "Real Madrid"] },
    { name: "Sergio Ramos", clubs: ["Sevilla", "Real Madrid", "PSG"] },
    { name: "Robert Lewandowski", clubs: ["Dortmund", "Bayern Munich", "Barcelona"] },
    { name: "Erling Haaland", clubs: ["Dortmund", "Manchester City"] },
    { name: "Kylian Mbappe", clubs: ["Monaco", "PSG", "Real Madrid"] },
    { name: "Nicolas Anelka", clubs: ["Arsenal", "Real Madrid", "PSG", "Liverpool", "Manchester City", "Chelsea", "Juventus"] },
    { name: "Alexis Sanchez", clubs: ["Udinese", "Barcelona", "Arsenal", "Manchester United", "Inter Milan", "Marseille"] },
    { name: "Pierre-Emerick Aubameyang", clubs: ["AC Milan", "Monaco", "Lille", "Saint-Etienne", "Dortmund", "Arsenal", "Barcelona", "Chelsea", "Marseille"] },
    { name: "Angel Di Maria", clubs: ["Real Madrid", "Manchester United", "PSG", "Juventus", "Benfica"] },
    { name: "James Rodriguez", clubs: ["Monaco", "Real Madrid", "Bayern Munich", "Everton"] },
    { name: "Cesc Fabregas", clubs: ["Arsenal", "Barcelona", "Chelsea", "Monaco"] },
    { name: "Samuel Eto'o", clubs: ["Real Madrid", "Barcelona", "Inter Milan", "Chelsea", "Everton", "Sampdoria"] },
    { name: "Gonzalo Higuain", clubs: ["Real Madrid", "Napoli", "Juventus", "AC Milan", "Chelsea"] },
    { name: "Alvaro Morata", clubs: ["Real Madrid", "Juventus", "Chelsea", "Atletico Madrid"] },
    { name: "Philippe Coutinho", clubs: ["Inter Milan", "Liverpool", "Barcelona", "Bayern Munich", "Aston Villa"] },
    { name: "Radamel Falcao", clubs: ["Atletico Madrid", "Monaco", "Manchester United", "Chelsea", "Rayo Vallecano"] },
    { name: "Mario Balotelli", clubs: ["Inter Milan", "Manchester City", "AC Milan", "Liverpool", "Nice", "Marseille"] },
    { name: "Arturo Vidal", clubs: ["Bayer Leverkusen", "Juventus", "Bayern Munich", "Barcelona", "Inter Milan"] },
    { name: "Dani Alves", clubs: ["Sevilla", "Barcelona", "Juventus", "PSG"] },
    { name: "Xabi Alonso", clubs: ["Real Sociedad", "Liverpool", "Real Madrid", "Bayern Munich"] },
    { name: "Andrea Pirlo", clubs: ["Inter Milan", "AC Milan", "Juventus"] },
    { name: "Toni Kroos", clubs: ["Bayern Munich", "Bayer Leverkusen", "Real Madrid"] },
    { name: "Mesut Ozil", clubs: ["Schalke 04", "Werder Bremen", "Real Madrid", "Arsenal"] },
    { name: "Kevin De Bruyne", clubs: ["Chelsea", "Werder Bremen", "Wolfsburg", "Manchester City"] },
    { name: "Thiago Silva", clubs: ["AC Milan", "PSG", "Chelsea"] },
    { name: "David Alaba", clubs: ["Bayern Munich", "Hoffenheim", "Real Madrid"] },
    { name: "Antonio Rudiger", clubs: ["Stuttgart", "Roma", "Chelsea", "Real Madrid"] },
    { name: "Joao Cancelo", clubs: ["Valencia", "Inter Milan", "Juventus", "Manchester City", "Bayern Munich", "Barcelona"] },
    { name: "Ivan Rakitic", clubs: ["Schalke 04", "Sevilla", "Barcelona"] },
    { name: "Casemiro", clubs: ["Real Madrid", "Manchester United"] },
    { name: "Paul Pogba", clubs: ["Manchester United", "Juventus"] },
    { name: "Eden Hazard", clubs: ["Lille", "Chelsea", "Real Madrid"] },
    { name: "Mohamed Salah", clubs: ["Chelsea", "Fiorentina", "Roma", "Liverpool"] },
    { name: "Sadio Mane", clubs: ["Southampton", "Liverpool", "Bayern Munich"] },
    { name: "Arjen Robben", clubs: ["Chelsea", "Real Madrid", "Bayern Munich"] },
    { name: "Franck Ribery", clubs: ["Marseille", "Bayern Munich", "Fiorentina"] },
    { name: "Gianluigi Buffon", clubs: ["Parma", "Juventus", "PSG"] },
    { name: "Thibaut Courtois", clubs: ["Atletico Madrid", "Chelsea", "Real Madrid"] },
    { name: "Keylor Navas", clubs: ["Levante", "Real Madrid", "PSG"] },
    { name: "Petr Cech", clubs: ["Rennes", "Chelsea", "Arsenal"] },
    { name: "Hugo Lloris", clubs: ["Nice", "Lyon", "Tottenham"] },
    { name: "Manuel Neuer", clubs: ["Schalke 04", "Bayern Munich"] },
    { name: "David De Gea", clubs: ["Atletico Madrid", "Manchester United", "Fiorentina"] },
    { name: "Wayne Rooney", clubs: ["Everton", "Manchester United"] },
    { name: "Frank Lampard", clubs: ["West Ham", "Chelsea", "Manchester City"] },
    { name: "Steven Gerrard", clubs: ["Liverpool"] },
    { name: "Harry Kane", clubs: ["Tottenham", "Bayern Munich"] },
    { name: "Raheem Sterling", clubs: ["Liverpool", "Manchester City", "Chelsea", "Arsenal"] },
    { name: "Jack Grealish", clubs: ["Aston Villa", "Manchester City"] },
    { name: "Riyad Mahrez", clubs: ["Leicester City", "Manchester City"] },
    { name: "N'Golo Kante", clubs: ["Leicester City", "Chelsea"] },
    { name: "Robin van Persie", clubs: ["Arsenal", "Manchester United"] },
    { name: "Carlos Tevez", clubs: ["West Ham", "Manchester United", "Manchester City", "Juventus"] },
    { name: "Antoine Griezmann", clubs: ["Real Sociedad", "Atletico Madrid", "Barcelona"] },
    { name: "David Silva", clubs: ["Valencia", "Manchester City", "Real Sociedad"] },
    { name: "Juan Mata", clubs: ["Chelsea", "Manchester United", "Valencia"] },
    { name: "Fernando Torres", clubs: ["Atletico Madrid", "Liverpool", "Chelsea", "AC Milan"] },
    { name: "Diego Forlan", clubs: ["Manchester United", "Villarreal", "Atletico Madrid", "Inter Milan"] },
    { name: "Patrick Vieira", clubs: ["AC Milan", "Arsenal", "Juventus", "Inter Milan", "Manchester City"] },
    { name: "Clarence Seedorf", clubs: ["Sampdoria", "Real Madrid", "Inter Milan", "AC Milan"] },
    { name: "Hernan Crespo", clubs: ["Parma", "Lazio", "Inter Milan", "Chelsea", "AC Milan"] },
    { name: "Jude Bellingham", clubs: ["Dortmund", "Real Madrid"] },
    { name: "Vinicius Junior", clubs: ["Real Madrid"] },
    { name: "Bukayo Saka", clubs: ["Arsenal"] },
    { name: "Phil Foden", clubs: ["Manchester City"] },
    { name: "Rodri", clubs: ["Villarreal", "Atletico Madrid", "Manchester City"] },
    { name: "Bernardo Silva", clubs: ["Monaco", "Manchester City"] },
    { name: "Bruno Fernandes", clubs: ["Udinese", "Sampdoria", "Manchester United"] },
    { name: "Edinson Cavani", clubs: ["Napoli", "PSG", "Manchester United", "Valencia"] },
    { name: "Ruud van Nistelrooy", clubs: ["Manchester United", "Real Madrid", "Hamburg", "Malaga"] },
    { name: "David Villa", clubs: ["Valencia", "Barcelona", "Atletico Madrid"] },
    { name: "Miroslav Klose", clubs: ["Werder Bremen", "Bayern Munich", "Lazio"] },
    { name: "Luca Toni", clubs: ["Fiorentina", "Bayern Munich", "Roma", "Juventus"] },
    { name: "Diego Costa", clubs: ["Atletico Madrid", "Chelsea", "Wolves"] },
    { name: "Romelu Lukaku", clubs: ["Chelsea", "Everton", "Manchester United", "Inter Milan", "Roma"] },
    { name: "Gabriel Jesus", clubs: ["Manchester City", "Arsenal"] },
    { name: "Darwin Nunez", clubs: ["Liverpool"] },
    { name: "Lautaro Martinez", clubs: ["Inter Milan"] },
    { name: "Victor Osimhen", clubs: ["Lille", "Napoli"] },
    { name: "Dusan Vlahovic", clubs: ["Fiorentina", "Juventus"] },
    { name: "Edin Dzeko", clubs: ["Wolfsburg", "Manchester City", "Roma", "Inter Milan"] },
    { name: "Olivier Giroud", clubs: ["Montpellier", "Arsenal", "Chelsea", "AC Milan"] },
    { name: "Mauro Icardi", clubs: ["Sampdoria", "Inter Milan", "PSG"] },
    { name: "Alvaro Negredo", clubs: ["Sevilla", "Manchester City", "Valencia"] },
    { name: "Roberto Firmino", clubs: ["Hoffenheim", "Liverpool"] },
    { name: "Ivan Perisic", clubs: ["Dortmund", "Wolfsburg", "Inter Milan", "Bayern Munich", "Tottenham"] },
    { name: "Christian Eriksen", clubs: ["Tottenham", "Inter Milan", "Brentford", "Manchester United"] },
    { name: "Miralem Pjanic", clubs: ["Lyon", "Roma", "Juventus", "Barcelona"] },
    { name: "Marco Verratti", clubs: ["PSG"] },
    { name: "Ilkay Gundogan", clubs: ["Dortmund", "Manchester City", "Barcelona"] },
    { name: "Declan Rice", clubs: ["West Ham", "Arsenal"] },
    { name: "Enzo Fernandez", clubs: ["Chelsea"] },
    { name: "Martin Odegaard", clubs: ["Real Madrid", "Real Sociedad", "Arsenal"] },
    { name: "Bruno Guimaraes", clubs: ["Lyon", "Newcastle"] },
    { name: "Gavi", clubs: ["Barcelona"] },
    { name: "Pedri", clubs: ["Barcelona"] },
    { name: "Thiago Alcantara", clubs: ["Barcelona", "Bayern Munich", "Liverpool"] },
    { name: "Sami Khedira", clubs: ["Stuttgart", "Real Madrid", "Juventus"] },
    { name: "Blaise Matuidi", clubs: ["Saint-Etienne", "PSG", "Juventus"] },
    { name: "Virgil van Dijk", clubs: ["Southampton", "Liverpool"] },
    { name: "Ruben Dias", clubs: ["Manchester City"] },
    { name: "Marquinhos", clubs: ["Roma", "PSG"] },
    { name: "Raphael Varane", clubs: ["Real Madrid", "Manchester United"] },
    { name: "Mats Hummels", clubs: ["Bayern Munich", "Dortmund", "Roma"] },
    { name: "Leonardo Bonucci", clubs: ["Juventus", "AC Milan", "Union Berlin"] },
    { name: "Giorgio Chiellini", clubs: ["Fiorentina", "Juventus"] },
    { name: "Gerard Pique", clubs: ["Manchester United", "Barcelona"] },
    { name: "Carles Puyol", clubs: ["Barcelona"] },
    { name: "Achraf Hakimi", clubs: ["Real Madrid", "Dortmund", "Inter Milan", "PSG"] },
    { name: "Theo Hernandez", clubs: ["Atletico Madrid", "Real Madrid", "Real Sociedad", "AC Milan"] },
    { name: "Alphonso Davies", clubs: ["Bayern Munich"] },
    { name: "Andrew Robertson", clubs: ["Liverpool"] },
    { name: "Trent Alexander-Arnold", clubs: ["Liverpool"] },
    { name: "Kyle Walker", clubs: ["Tottenham", "Aston Villa", "Manchester City"] },
    { name: "John Stones", clubs: ["Everton", "Manchester City"] },
    { name: "Kalidou Koulibaly", clubs: ["Napoli", "Chelsea"] },
    { name: "Jules Kounde", clubs: ["Sevilla", "Barcelona"] },
    { name: "Alisson Becker", clubs: ["Roma", "Liverpool"] },
    { name: "Ederson", clubs: ["Manchester City"] },
    { name: "Jan Oblak", clubs: ["Atletico Madrid"] },
    { name: "Marc-Andre ter Stegen", clubs: ["Monchengladbach", "Barcelona"] },
    { name: "Mike Maignan", clubs: ["Lille", "AC Milan"] },
    { name: "Emiliano Martinez", clubs: ["Arsenal", "Getafe", "Aston Villa"] },
    { name: "Gianluigi Donnarumma", clubs: ["AC Milan", "PSG"] },
    { name: "Yann Sommer", clubs: ["Monchengladbach", "Bayern Munich", "Inter Milan"] },
    { name: "Alessandro Del Piero", clubs: ["Juventus"] },
    { name: "Francesco Totti", clubs: ["Roma"] },
    { name: "Paul Scholes", clubs: ["Manchester United"] },
    { name: "Ryan Giggs", clubs: ["Manchester United"] },
    { name: "Pavel Nedved", clubs: ["Lazio", "Juventus"] },
    { name: "Filippo Inzaghi", clubs: ["Juventus", "AC Milan"] },
    { name: "Andriy Shevchenko", clubs: ["AC Milan", "Chelsea"] },
    { name: "Kaka", clubs: ["AC Milan", "Real Madrid"] },
    { name: "Michael Ballack", clubs: ["Bayer Leverkusen", "Bayern Munich", "Chelsea"] },
    { name: "Didier Drogba", clubs: ["Marseille", "Chelsea"] },
    { name: "Claude Makelele", clubs: ["Real Madrid", "Chelsea", "PSG"] },
    { name: "Roberto Carlos", clubs: ["Real Madrid"] },
    { name: "Luis Figo", clubs: ["Barcelona", "Real Madrid", "Inter Milan"] },
    { name: "David Beckham", clubs: ["Manchester United", "Real Madrid", "AC Milan", "PSG"] },
    { name: "Fabio Cannavaro", clubs: ["Parma", "Inter Milan", "Juventus", "Real Madrid"] },
    { name: "Gianluca Zambrotta", clubs: ["Juventus", "Barcelona", "AC Milan"] },
    { name: "Serge Gnabry", clubs: ["Arsenal", "Werder Bremen", "Hoffenheim", "Bayern Munich"] },
    { name: "Kingsley Coman", clubs: ["PSG", "Juventus", "Bayern Munich"] },
    { name: "Ousmane Dembele", clubs: ["Rennes", "Dortmund", "Barcelona", "PSG"] },
    { name: "Rafael Leao", clubs: ["Lille", "AC Milan"] },
    { name: "Khvicha Kvaratskhelia", clubs: ["Napoli"] },
    { name: "Marcus Rashford", clubs: ["Manchester United"] },
    { name: "Luis Diaz", clubs: ["Liverpool"] },
    { name: "Federico Chiesa", clubs: ["Fiorentina", "Juventus", "Liverpool"] },
    { name: "Juninho Pernambucano", clubs: ["Lyon"] },
    { name: "Michael Essien", clubs: ["Lyon", "Chelsea", "Real Madrid", "AC Milan"] },
    { name: "Florent Malouda", clubs: ["Lyon", "Chelsea"] },
    { name: "Eric Abidal", clubs: ["Lyon", "Barcelona", "Monaco"] },
    { name: "Ludovic Giuly", clubs: ["Monaco", "Barcelona", "Roma", "PSG"] },
    { name: "Dimitar Berbatov", clubs: ["Bayer Leverkusen", "Tottenham", "Manchester United", "Monaco"] },
    { name: "Klaas-Jan Huntelaar", clubs: ["Real Madrid", "AC Milan", "Schalke 04"] },
    { name: "Raul", clubs: ["Real Madrid", "Schalke 04"] },
    { name: "Lukas Podolski", clubs: ["Bayern Munich", "Arsenal", "Inter Milan"] },
    { name: "Shinji Kagawa", clubs: ["Dortmund", "Manchester United"] },
    { name: "Mario Gotze", clubs: ["Dortmund", "Bayern Munich", "Frankfurt"] },
    { name: "Marco Reus", clubs: ["Monchengladbach", "Dortmund"] },
    { name: "Joaquin", clubs: ["Real Betis", "Valencia", "Fiorentina", "Malaga"] },
    { name: "Isco", clubs: ["Malaga", "Real Madrid", "Sevilla", "Real Betis"] },
    { name: "Marcos Senna", clubs: ["Villarreal"] },
    { name: "Juan Roman Riquelme", clubs: ["Barcelona", "Villarreal"] },
    { name: "Antonio Cassano", clubs: ["Roma", "Real Madrid", "Sampdoria", "AC Milan", "Inter Milan", "Parma"] },
    { name: "Alberto Gilardino", clubs: ["Parma", "AC Milan", "Fiorentina", "Genoa", "Bologna"] },
    { name: "Adrian Mutu", clubs: ["Inter Milan", "Parma", "Juventus", "Fiorentina"] },
    { name: "Sergej Milinkovic-Savic", clubs: ["Lazio"] },
    { name: "Luis Alberto", clubs: ["Liverpool", "Malaga", "Lazio"] },
    { name: "Marek Hamsik", clubs: ["Napoli"] },
    { name: "Lorenzo Insigne", clubs: ["Napoli"] },
    { name: "Dries Mertens", clubs: ["Napoli"] },
    { name: "Jamie Vardy", clubs: ["Leicester City"] },
    { name: "Kasper Schmeichel", clubs: ["Manchester City", "Leicester City", "Nice"] },
    { name: "Wes Morgan", clubs: ["Leicester City"] },
    { name: "Wilfried Zaha", clubs: ["Manchester United", "Crystal Palace", "Lyon"] },
    { name: "Christian Benteke", clubs: ["Aston Villa", "Liverpool", "Crystal Palace"] },
    { name: "Gareth Barry", clubs: ["Aston Villa", "Manchester City", "Everton"] },
    { name: "Leighton Baines", clubs: ["Everton"] },
    { name: "Tim Cahill", clubs: ["Everton"] },
    { name: "Phil Jagielka", clubs: ["Everton", "Sheffield United"] },
    { name: "Jermain Defoe", clubs: ["West Ham", "Tottenham", "Portsmouth", "Sunderland"] },
    { name: "Paolo Di Canio", clubs: ["AC Milan", "Juventus", "Napoli", "West Ham"] },
    { name: "Tomas Rosicky", clubs: ["Dortmund", "Arsenal"] },
    { name: "Mikel Arteta", clubs: ["Everton", "Arsenal"] },
    { name: "Rio Ferdinand", clubs: ["West Ham", "Leeds United", "Manchester United"] },
    { name: "John Terry", clubs: ["Chelsea", "Aston Villa"] },
    { name: "Ricardo Carvalho", clubs: ["Chelsea", "Real Madrid", "Monaco"] },
    { name: "Vincent Kompany", clubs: ["Manchester City"] },
    { name: "Pablo Zabaleta", clubs: ["Espanyol", "Manchester City", "West Ham"] },
    { name: "Branislav Ivanovic", clubs: ["Chelsea"] },
    { name: "Gary Neville", clubs: ["Manchester United"] },
    { name: "Jamie Carragher", clubs: ["Liverpool"] },
    { name: "Philipp Lahm", clubs: ["Bayern Munich", "Stuttgart"] },
    { name: "Bixente Lizarazu", clubs: ["Bayern Munich", "Marseille"] },
    { name: "Willy Sagnol", clubs: ["Monaco", "Bayern Munich"] },
    { name: "Lilian Thuram", clubs: ["Monaco", "Parma", "Juventus", "Barcelona"] },
    { name: "Alessandro Nesta", clubs: ["Lazio", "AC Milan"] },
    { name: "Javier Zanetti", clubs: ["Inter Milan"] },
    { name: "Marco Materazzi", clubs: ["Everton", "Inter Milan"] },
    { name: "Maicon", clubs: ["Monaco", "Inter Milan", "Manchester City", "Roma"] },
    { name: "Edwin van der Sar", clubs: ["Juventus", "Fulham", "Manchester United"] },
    { name: "Victor Valdes", clubs: ["Barcelona", "Manchester United"] },
    { name: "Pepe Reina", clubs: ["Barcelona", "Villarreal", "Liverpool", "Napoli", "Bayern Munich", "AC Milan", "Aston Villa", "Lazio"] },
    { name: "Joe Hart", clubs: ["Manchester City", "Torino", "West Ham", "Tottenham"] },
    { name: "Julio Cesar", clubs: ["Inter Milan"] },
    { name: "Dida", clubs: ["AC Milan"] },
    { name: "Fabien Barthez", clubs: ["Marseille", "Monaco", "Manchester United"] },
    { name: "Jesus Navas", clubs: ["Sevilla", "Manchester City"] },
    { name: "Gerard Moreno", clubs: ["Villarreal", "Espanyol"] },
    { name: "Pau Torres", clubs: ["Villarreal", "Aston Villa"] },
    { name: "Yeremy Pino", clubs: ["Villarreal"] },
    { name: "Mikel Oyarzabal", clubs: ["Real Sociedad"] },
    { name: "Alexander Isak", clubs: ["Dortmund", "Real Sociedad", "Newcastle"] },
    { name: "Iago Aspas", clubs: ["Celta Vigo", "Liverpool", "Sevilla"] },
    { name: "Frederic Kanoute", clubs: ["West Ham", "Tottenham", "Sevilla"] },
    { name: "Luis Fabiano", clubs: ["Sevilla"] },
    { name: "Josip Ilicic", clubs: ["Palermo", "Fiorentina", "Atalanta"] },
    { name: "Alejandro Gomez", clubs: ["Atalanta", "Sevilla"] },
    { name: "Duvan Zapata", clubs: ["Napoli", "Udinese", "Sampdoria", "Atalanta", "Torino"] },
    { name: "Luis Muriel", clubs: ["Udinese", "Sampdoria", "Sevilla", "Fiorentina", "Atalanta"] },
    { name: "Domenico Berardi", clubs: ["Sassuolo", "Juventus"] },
    { name: "Giacomo Raspadori", clubs: ["Sassuolo", "Napoli"] },
    { name: "Federico Bernardeschi", clubs: ["Fiorentina", "Juventus"] },
    { name: "Antonio Candreva", clubs: ["Juventus", "Lazio", "Inter Milan", "Sampdoria"] },
    { name: "Lucas Leiva", clubs: ["Liverpool", "Lazio"] },
    { name: "Joaquin Correa", clubs: ["Sampdoria", "Sevilla", "Lazio", "Inter Milan", "Marseille"] },
    { name: "Felipe Anderson", clubs: ["Lazio", "West Ham", "Porto"] },
    { name: "Stevan Jovetic", clubs: ["Fiorentina", "Manchester City", "Inter Milan", "Sevilla", "Monaco", "Hertha Berlin"] },
    { name: "Son Heung-min", clubs: ["Bayer Leverkusen", "Tottenham"] },
    { name: "Richarlison", clubs: ["Everton", "Tottenham"] },
    { name: "James Maddison", clubs: ["Leicester City", "Tottenham"] },
    { name: "Youri Tielemans", clubs: ["Monaco", "Leicester City", "Aston Villa"] },
    { name: "Wilfred Ndidi", clubs: ["Leicester City"] },
    { name: "Harvey Barnes", clubs: ["Leicester City", "Newcastle"] },
    { name: "Callum Wilson", clubs: ["Bournemouth", "Newcastle"] },
    { name: "Allan Saint-Maximin", clubs: ["Nice", "Newcastle"] },
    { name: "Joelinton", clubs: ["Hoffenheim", "Newcastle"] },
    { name: "Ollie Watkins", clubs: ["Aston Villa"] },
    { name: "Emiliano Buendia", clubs: ["Getafe", "Aston Villa"] },
    { name: "Leon Bailey", clubs: ["Bayer Leverkusen", "Aston Villa"] },
    { name: "Douglas Luiz", clubs: ["Girona", "Aston Villa", "Juventus"] },
    { name: "Patrik Schick", clubs: ["Sampdoria", "Roma", "RB Leipzig", "Bayer Leverkusen"] },
    { name: "Christopher Nkunku", clubs: ["PSG", "RB Leipzig", "Chelsea"] },
    { name: "Timo Werner", clubs: ["Stuttgart", "RB Leipzig", "Chelsea", "Tottenham"] },
    { name: "Dani Olmo", clubs: ["RB Leipzig", "Barcelona"] },
    { name: "Dominik Szoboszlai", clubs: ["RB Leipzig", "Liverpool"] },
    { name: "Dayot Upamecano", clubs: ["RB Leipzig", "Bayern Munich"] },
    { name: "Ibrahima Konate", clubs: ["RB Leipzig", "Liverpool"] },
    { name: "Jonathan David", clubs: ["Lille"] },
    { name: "Renato Sanches", clubs: ["Bayern Munich", "Swansea", "Lille", "PSG", "Roma"] },
    { name: "Burak Yilmaz", clubs: ["Lille"] },
    { name: "Wissam Ben Yedder", clubs: ["Sevilla", "Monaco"] },
    { name: "Aurelien Tchouameni", clubs: ["Bordeaux", "Monaco", "Real Madrid"] },
    { name: "Dimitri Payet", clubs: ["Saint-Etienne", "Lille", "Marseille", "West Ham"] },
    { name: "Florian Thauvin", clubs: ["Lille", "Marseille", "Newcastle"] }
];
