const playersData = [
    // --- Գերաստղեր և Լեգենդներ ---
    { name: "Cristiano Ronaldo", clubs: ["Manchester United", "Real Madrid", "Juventus"] },
    { name: "Lionel Messi", clubs: ["Barcelona", "PSG"] },
    { name: "Zlatan Ibrahimovic", clubs: ["Juventus", "Inter Milan", "Barcelona", "AC Milan", "PSG", "Manchester United"] },
    { name: "Ronaldo Nazario", clubs: ["Barcelona", "Inter Milan", "Real Madrid", "AC Milan"] },
    { name: "Ronaldinho", clubs: ["PSG", "Barcelona", "AC Milan"] },
    { name: "Zinedine Zidane", clubs: ["Juventus", "Real Madrid"] },
    { name: "Thierry Henry", clubs: ["Juventus", "Arsenal", "Barcelona"] },
    { name: "Luis Suarez", clubs: ["Liverpool", "Barcelona", "Atletico Madrid"] },
    { name: "Neymar Jr", clubs: ["Barcelona", "PSG"] },
    { name: "Karim Benzema", clubs: ["Lyon", "Real Madrid"] },
    { name: "Gareth Bale", clubs: ["Tottenham", "Real Madrid"] },
    { name: "Luka Modric", clubs: ["Tottenham", "Real Madrid"] },
    { name: "Sergio Ramos", clubs: ["Sevilla", "Real Madrid", "PSG"] },
    { name: "Robert Lewandowski", clubs: ["Dortmund", "Bayern Munich", "Barcelona"] },
    { name: "Erling Haaland", clubs: ["Dortmund", "Manchester City"] },
    { name: "Kylian Mbappe", clubs: ["Monaco", "PSG", "Real Madrid"] },
    { name: "Antoine Griezmann", clubs: ["Real Sociedad", "Atletico Madrid", "Barcelona"] },
    { name: "David Beckham", clubs: ["Manchester United", "Real Madrid", "AC Milan", "PSG"] },
    { name: "Kaka", clubs: ["AC Milan", "Real Madrid"] },
    { name: "Andriy Shevchenko", clubs: ["AC Milan", "Chelsea"] },
    { name: "Xavi Hernandez", clubs: ["Barcelona"] },
    { name: "Andres Iniesta", clubs: ["Barcelona"] },

    // --- Ճամփորդողներ (Շատ ակումբներ փոխած) ---
    { name: "Nicolas Anelka", clubs: ["Arsenal", "Real Madrid", "PSG", "Liverpool", "Manchester City", "Chelsea", "Juventus"] },
    { name: "Alexis Sanchez", clubs: ["Udinese", "Barcelona", "Arsenal", "Manchester United", "Inter Milan", "Marseille"] },
    { name: "Pierre-Emerick Aubameyang", clubs: ["AC Milan", "Monaco", "Lille", "Saint-Etienne", "Dortmund", "Arsenal", "Barcelona", "Chelsea", "Marseille"] },
    { name: "Angel Di Maria", clubs: ["Real Madrid", "Manchester United", "PSG", "Juventus", "Benfica"] },
    { name: "James Rodriguez", clubs: ["Monaco", "Real Madrid", "Bayern Munich", "Everton"] },
    { name: "Cesc Fabregas", clubs: ["Arsenal", "Barcelona", "Chelsea", "Monaco"] },
    { name: "Samuel Eto'o", clubs: ["Real Madrid", "Barcelona", "Inter Milan", "Chelsea", "Everton", "Sampdoria"] },
    { name: "Gonzalo Higuain", clubs: ["Real Madrid", "Napoli", "Juventus", "AC Milan", "Chelsea"] },
    { name: "Alvaro Morata", clubs: ["Real Madrid", "Juventus", "Chelsea", "Atletico Madrid"] },
    { name: "Philippe Coutinho", clubs: ["Inter Milan", "Liverpool", "Barcelona", "Bayern Munich", "Aston Villa"] },
    { name: "Radamel Falcao", clubs: ["Atletico Madrid", "Monaco", "Manchester United", "Chelsea"] },
    { name: "Mario Balotelli", clubs: ["Inter Milan", "Manchester City", "AC Milan", "Liverpool", "Nice", "Marseille"] },
    { name: "Arturo Vidal", clubs: ["Bayer Leverkusen", "Juventus", "Bayern Munich", "Barcelona", "Inter Milan"] },
    { name: "Dani Alves", clubs: ["Sevilla", "Barcelona", "Juventus", "PSG"] },
    { name: "Romelu Lukaku", clubs: ["Chelsea", "Everton", "Manchester United", "Inter Milan", "Roma"] },
    { name: "Mateo Kovacic", clubs: ["Inter Milan", "Real Madrid", "Chelsea", "Manchester City"] },
    { name: "Pedro", clubs: ["Barcelona", "Chelsea", "Roma", "Lazio"] },
    { name: "Joao Cancelo", clubs: ["Valencia", "Inter Milan", "Juventus", "Manchester City", "Bayern Munich", "Barcelona"] },

    // --- Կիսապաշտպաններ և Պաշտպաններ ---
    { name: "Xabi Alonso", clubs: ["Real Sociedad", "Liverpool", "Real Madrid", "Bayern Munich"] },
    { name: "Andrea Pirlo", clubs: ["Inter Milan", "AC Milan", "Juventus"] },
    { name: "Toni Kroos", clubs: ["Bayern Munich", "Bayer Leverkusen", "Real Madrid"] },
    { name: "Mesut Ozil", clubs: ["Schalke 04", "Werder Bremen", "Real Madrid", "Arsenal"] },
    { name: "Kevin De Bruyne", clubs: ["Chelsea", "Werder Bremen", "Wolfsburg", "Manchester City"] },
    { name: "Thiago Silva", clubs: ["AC Milan", "PSG", "Chelsea"] },
    { name: "David Alaba", clubs: ["Bayern Munich", "Hoffenheim", "Real Madrid"] },
    { name: "Antonio Rudiger", clubs: ["Stuttgart", "Roma", "Chelsea", "Real Madrid"] },
    { name: "Casemiro", clubs: ["Real Madrid", "Manchester United"] },
    { name: "Paul Pogba", clubs: ["Manchester United", "Juventus"] },
    { name: "Eden Hazard", clubs: ["Lille", "Chelsea", "Real Madrid"] },
    { name: "Mohamed Salah", clubs: ["Chelsea", "Fiorentina", "Roma", "Liverpool"] },
    { name: "Sadio Mane", clubs: ["Southampton", "Liverpool", "Bayern Munich"] },
    { name: "Arjen Robben", clubs: ["Chelsea", "Real Madrid", "Bayern Munich"] },
    { name: "Franck Ribery", clubs: ["Marseille", "Bayern Munich", "Fiorentina"] },
    { name: "Virgil van Dijk", clubs: ["Southampton", "Liverpool"] },
    { name: "Sergio Busquets", clubs: ["Barcelona"] },
    { name: "Lothar Matthaus", clubs: ["Bayern Munich", "Inter Milan"] },

    // --- Հարձակվողներ և Ռմբարկուներ ---
    { name: "Edinson Cavani", clubs: ["Napoli", "PSG", "Manchester United", "Valencia"] },
    { name: "Ruud van Nistelrooy", clubs: ["Manchester United", "Real Madrid", "Hamburg", "Malaga"] },
    { name: "David Villa", clubs: ["Valencia", "Barcelona", "Atletico Madrid"] },
    { name: "Miroslav Klose", clubs: ["Werder Bremen", "Bayern Munich", "Lazio"] },
    { name: "Luca Toni", clubs: ["Fiorentina", "Bayern Munich", "Roma", "Juventus"] },
    { name: "Diego Costa", clubs: ["Atletico Madrid", "Chelsea", "Wolves"] },
    { name: "Gabriel Jesus", clubs: ["Manchester City", "Arsenal"] },
    { name: "Darwin Nunez", clubs: ["Liverpool"] },
    { name: "Lautaro Martinez", clubs: ["Inter Milan"] },
    { name: "Victor Osimhen", clubs: ["Lille", "Napoli"] },
    { name: "Dusan Vlahovic", clubs: ["Fiorentina", "Juventus"] },
    { name: "Edin Dzeko", clubs: ["Wolfsburg", "Manchester City", "Roma", "Inter Milan"] },
    { name: "Olivier Giroud", clubs: ["Montpellier", "Arsenal", "Chelsea", "AC Milan"] },
    { name: "Mauro Icardi", clubs: ["Sampdoria", "Inter Milan", "PSG"] },
    { name: "Roberto Firmino", clubs: ["Hoffenheim", "Liverpool"] },
    { name: "Harry Kane", clubs: ["Tottenham", "Bayern Munich"] },
    { name: "Son Heung-min", clubs: ["Bayer Leverkusen", "Tottenham"] },

    // --- Լեգենդներ (2000-2020) ---
    { name: "Alessandro Del Piero", clubs: ["Juventus"] },
    { name: "Francesco Totti", clubs: ["Roma"] },
    { name: "Steven Gerrard", clubs: ["Liverpool"] },
    { name: "Frank Lampard", clubs: ["West Ham", "Chelsea", "Manchester City"] },
    { name: "Paul Scholes", clubs: ["Manchester United"] },
    { name: "Ryan Giggs", clubs: ["Manchester United"] },
    { name: "John Terry", clubs: ["Chelsea", "Aston Villa"] },
    { name: "Wayne Rooney", clubs: ["Everton", "Manchester United"] },
    { name: "Didier Drogba", clubs: ["Marseille", "Chelsea"] },
    { name: "Patrick Vieira", clubs: ["AC Milan", "Arsenal", "Juventus", "Inter Milan", "Manchester City"] },
    { name: "Clarence Seedorf", clubs: ["Sampdoria", "Real Madrid", "Inter Milan", "AC Milan"] },
    { name: "Hernan Crespo", clubs: ["Parma", "Lazio", "Inter Milan", "Chelsea", "AC Milan"] },
    { name: "Fabio Cannavaro", clubs: ["Parma", "Inter Milan", "Juventus", "Real Madrid"] },
    { name: "Rio Ferdinand", clubs: ["West Ham", "Leeds United", "Manchester United"] },
    { name: "Carles Puyol", clubs: ["Barcelona"] },
    { name: "Philipp Lahm", clubs: ["Bayern Munich", "Stuttgart"] },

    // --- Ժամանակակից աստղեր ---
    { name: "Jude Bellingham", clubs: ["Dortmund", "Real Madrid"] },
    { name: "Vinicius Junior", clubs: ["Real Madrid"] },
    { name: "Bukayo Saka", clubs: ["Arsenal"] },
    { name: "Phil Foden", clubs: ["Manchester City"] },
    { name: "Rodri", clubs: ["Villarreal", "Atletico Madrid", "Manchester City"] },
    { name: "Bernardo Silva", clubs: ["Monaco", "Manchester City"] },
    { name: "Bruno Fernandes", clubs: ["Udinese", "Sampdoria", "Manchester United"] },
    { name: "Martin Odegaard", clubs: ["Real Madrid", "Real Sociedad", "Arsenal"] },
    { name: "Declan Rice", clubs: ["West Ham", "Arsenal"] },
    { name: "Ilkay Gundogan", clubs: ["Dortmund", "Manchester City", "Barcelona"] },
    { name: "Leroy Sane", clubs: ["Schalke 04", "Manchester City", "Bayern Munich"] },
    { name: "Rafael Leao", clubs: ["Lille", "AC Milan"] },
    { name: "Khvicha Kvaratskhelia", clubs: ["Napoli"] },
    { name: "Lamine Yamal", clubs: ["Barcelona"] },
    { name: "Federico Chiesa", clubs: ["Fiorentina", "Juventus", "Liverpool"] },

    // --- Դարպասապահներ ---
    { name: "Gianluigi Buffon", clubs: ["Parma", "Juventus", "PSG"] },
    { name: "Iker Casillas", clubs: ["Real Madrid"] },
    { name: "Manuel Neuer", clubs: ["Schalke 04", "Bayern Munich"] },
    { name: "Petr Cech", clubs: ["Rennes", "Chelsea", "Arsenal"] },
    { name: "Thibaut Courtois", clubs: ["Atletico Madrid", "Chelsea", "Real Madrid"] },
    { name: "Alisson Becker", clubs: ["Roma", "Liverpool"] },
    { name: "Ederson", clubs: ["Manchester City"] },
    { name: "David De Gea", clubs: ["Atletico Madrid", "Manchester United", "Fiorentina"] },
    { name: "Jan Oblak", clubs: ["Atletico Madrid"] },
    { name: "Hugo Lloris", clubs: ["Nice", "Lyon", "Tottenham"] },
    { name: "Keylor Navas", clubs: ["Levante", "Real Madrid", "PSG"] },

    // --- Լրացուցիչ ճանաչված խաղացողներ ---
    { name: "Jamie Vardy", clubs: ["Leicester City"] },
    { name: "Riyad Mahrez", clubs: ["Leicester City", "Manchester City"] },
    { name: "N'Golo Kante", clubs: ["Leicester City", "Chelsea"] },
    { name: "David Silva", clubs: ["Valencia", "Manchester City", "Real Sociedad"] },
    { name: "Juan Mata", clubs: ["Valencia", "Chelsea", "Manchester United"] },
    { name: "Fernando Torres", clubs: ["Atletico Madrid", "Liverpool", "Chelsea", "AC Milan"] },
    { name: "Carlos Tevez", clubs: ["West Ham", "Manchester United", "Manchester City", "Juventus"] },
    { name: "Dimitri Payet", clubs: ["Saint-Etienne", "Lille", "Marseille", "West Ham"] },
    { name: "Mikel Arteta", clubs: ["Everton", "Arsenal"] },
    { name: "Ashley Young", clubs: ["Aston Villa", "Manchester United", "Inter Milan", "Everton"] },
    { name: "James Milner", clubs: ["Leeds United", "Newcastle", "Aston Villa", "Manchester City", "Liverpool", "Brighton"] },
    { name: "Ivan Rakitic", clubs: ["Schalke 04", "Sevilla", "Barcelona"] },
    { name: "Dani Parejo", clubs: ["Real Madrid", "Getafe", "Valencia", "Villarreal"] },
    { name: "Joaquin", clubs: ["Real Betis", "Valencia", "Fiorentina", "Malaga"] },
    { name: "Isco", clubs: ["Malaga", "Real Madrid", "Sevilla", "Real Betis"] },
    { name: "Marco Reus", clubs: ["Monchengladbach", "Dortmund"] },
    { name: "Thomas Muller", clubs: ["Bayern Munich"] }
];
